name: sqlite_statements
description: SQLite code annotations for entities.
version: 1.0.0
homepage: https://github.com/bitsydarel/sqlite_annotations
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  sqlite_statements_generator:
    path:
      sqlite_statements_generator
  build_runner: ^1.4.0
  pedantic: ^1.0.0
  test: ^1.0.0
