name: sqlite_annotations
description: SQLite code annotations for entities.
version: 1.0.0
# homepage: https://www.example.com
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  sqlite_generator:
    path:
      sqlite_generator
  build_runner: ^1.4.0
  pedantic: ^1.0.0
  test: ^1.0.0
