targets:
  $default:
    builders:
      sqlite_generator:

builders:
  sqlite_generator:
    target: ":sqlite_generator"
    import: "package:sqlite_generator/builder.dart"
    builder_factories: ["sqliteGenerator"]
    build_extensions: {".dart": ["sqlite_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]